services:
  postgres:
    image: 'postgres:latest'
    container_name: 'SecuriteNational'
    restart: 'always'
    environment:
      - 'POSTGRES_DB=securite'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5435:5432'

  adminer:
    image: adminer
    container_name: securite
    restart: always
    ports:
      - '8088:8080'